version: '1.0'
services:
  lazybean:
    image: vandereer/lazy-beancount:latest
    user: "${UID}:${GID}"
    ports:
      - "5003:5000"
      - "8101:8101"
      - "8777:8501"
    volumes:
      - .:/workspace
    environment:
      - FAVA_PORT=5003
      - BEANCOUNT_IMPORT_PORT=8101
      - LAZY_BEANCOUNT_HOST=localhost
      - LAZY_BEANCOUNT_PORT=8777
